repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.0.0
      hooks:
        - id: check-added-large-files
          args: ["--maxkb=1024"]
        - id: trailing-whitespace
        - id: check-byte-order-marker
        - id: check-case-conflict
        - id: check-json
        - id: check-merge-conflict
        - id: check-symlinks
        - id: check-xml
        - id: check-yaml
          args: ["--unsafe"]
        - id: detect-aws-credentials
          args: ["--allow-missing-credentials"]
        - id: detect-private-key
        - id: end-of-file-fixer
        - id: forbid-new-submodules
        - id: mixed-line-ending
        - id: no-commit-to-branch
          args: ["--branch", "develop", "--branch", "master"]
        - id: pretty-format-json
          args: ["--autofix", "--indent","2", "--top-keys", "id"]
